name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby: ['jruby', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
